server:
  port: 8888

spring:
  application:
    name: config
  #profiles:
    #active: dev,git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Linxfeng/config-repo.git
          search-paths: /
          #username: xxx
          #password: xxx
  rabbitmq:
    host: localhost
    #username: xxx
    #password: xxx
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#暴露bus-refresh接口，实现配置动态刷新
management:
  endpoints:
    web:
      expose: "*"
