server:
  port: 8081
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ticketsale?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  cloud:
    config:
      discovery:
        service-id: CONFIG
        enabled: true
  rabbitmq:
    host: localhost
    username: xxx
    password: xxx
    port: 5672
  redis:
    host: localhost
    port: 6379
    password: xxx
    timeout: 300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
